/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVehiclesRouteImport } from './routes/api/vehicles'
import { Route as ApiFillupsRouteImport } from './routes/api/fillups'
import { Route as ApiVehiclesIdRouteImport } from './routes/api/vehicles.$id'
import { Route as ApiFillupsIdRouteImport } from './routes/api/fillups.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVehiclesRoute = ApiVehiclesRouteImport.update({
  id: '/api/vehicles',
  path: '/api/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFillupsRoute = ApiFillupsRouteImport.update({
  id: '/api/fillups',
  path: '/api/fillups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVehiclesIdRoute = ApiVehiclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiVehiclesRoute,
} as any)
const ApiFillupsIdRoute = ApiFillupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiFillupsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/fillups': typeof ApiFillupsRouteWithChildren
  '/api/vehicles': typeof ApiVehiclesRouteWithChildren
  '/api/fillups/$id': typeof ApiFillupsIdRoute
  '/api/vehicles/$id': typeof ApiVehiclesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/fillups': typeof ApiFillupsRouteWithChildren
  '/api/vehicles': typeof ApiVehiclesRouteWithChildren
  '/api/fillups/$id': typeof ApiFillupsIdRoute
  '/api/vehicles/$id': typeof ApiVehiclesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/fillups': typeof ApiFillupsRouteWithChildren
  '/api/vehicles': typeof ApiVehiclesRouteWithChildren
  '/api/fillups/$id': typeof ApiFillupsIdRoute
  '/api/vehicles/$id': typeof ApiVehiclesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/fillups'
    | '/api/vehicles'
    | '/api/fillups/$id'
    | '/api/vehicles/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/fillups'
    | '/api/vehicles'
    | '/api/fillups/$id'
    | '/api/vehicles/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/fillups'
    | '/api/vehicles'
    | '/api/fillups/$id'
    | '/api/vehicles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiFillupsRoute: typeof ApiFillupsRouteWithChildren
  ApiVehiclesRoute: typeof ApiVehiclesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vehicles': {
      id: '/api/vehicles'
      path: '/api/vehicles'
      fullPath: '/api/vehicles'
      preLoaderRoute: typeof ApiVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fillups': {
      id: '/api/fillups'
      path: '/api/fillups'
      fullPath: '/api/fillups'
      preLoaderRoute: typeof ApiFillupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vehicles/$id': {
      id: '/api/vehicles/$id'
      path: '/$id'
      fullPath: '/api/vehicles/$id'
      preLoaderRoute: typeof ApiVehiclesIdRouteImport
      parentRoute: typeof ApiVehiclesRoute
    }
    '/api/fillups/$id': {
      id: '/api/fillups/$id'
      path: '/$id'
      fullPath: '/api/fillups/$id'
      preLoaderRoute: typeof ApiFillupsIdRouteImport
      parentRoute: typeof ApiFillupsRoute
    }
  }
}

interface ApiFillupsRouteChildren {
  ApiFillupsIdRoute: typeof ApiFillupsIdRoute
}

const ApiFillupsRouteChildren: ApiFillupsRouteChildren = {
  ApiFillupsIdRoute: ApiFillupsIdRoute,
}

const ApiFillupsRouteWithChildren = ApiFillupsRoute._addFileChildren(
  ApiFillupsRouteChildren,
)

interface ApiVehiclesRouteChildren {
  ApiVehiclesIdRoute: typeof ApiVehiclesIdRoute
}

const ApiVehiclesRouteChildren: ApiVehiclesRouteChildren = {
  ApiVehiclesIdRoute: ApiVehiclesIdRoute,
}

const ApiVehiclesRouteWithChildren = ApiVehiclesRoute._addFileChildren(
  ApiVehiclesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiFillupsRoute: ApiFillupsRouteWithChildren,
  ApiVehiclesRoute: ApiVehiclesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
